using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RetailOps.Infrastructure.Legacy.Persistence.Entities;

namespace RetailOps.Infrastructure.Legacy.Persistence;

public static class LegacyDatabaseBootstrap
{
    public static async Task EnsureDevSchemaAsync(IServiceProvider services, CancellationToken ct = default)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<LegacySasDbContext>();

        await db.Database.EnsureCreatedAsync(ct);
        await WidenLegacyColumnsAsync(db, ct);
        await EnsureStoreSettingsSchemaAsync(db, ct);
        await EnsureCrmSchemaAsync(db, ct);
        await EnsureCatalogSchemaAsync(db, ct);
        await EnsureSalesSchemaAsync(db, ct);
        await SeedGlobalConfigAsync(db, ct);
    }

    private static async Task EnsureStoreSettingsSchemaAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE IF EXISTS config
              ADD COLUMN IF NOT EXISTS nome_sistema varchar(100),
              ADD COLUMN IF NOT EXISTS contatos varchar(200),
              ADD COLUMN IF NOT EXISTS cnpj_sistema varchar(20),
              ADD COLUMN IF NOT EXISTS endereco varchar(200),
              ADD COLUMN IF NOT EXISTS tipo_rel varchar(10),
              ADD COLUMN IF NOT EXISTS tipo_desconto varchar(10),
              ADD COLUMN IF NOT EXISTS comissao numeric,
              ADD COLUMN IF NOT EXISTS token varchar(100),
              ADD COLUMN IF NOT EXISTS foto_rel varchar(200);

            CREATE TABLE IF NOT EXISTS forma_pgtos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(50) NOT NULL,
                acrescimo numeric DEFAULT 0,
                ativo varchar(3) DEFAULT 'Sim'
            );

            CREATE TABLE IF NOT EXISTS caixas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(50) NOT NULL,
                status varchar(10) DEFAULT 'Fechado',
                operador integer
            );
            """,
            ct);
    }

    private static async Task EnsureCrmSchemaAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS clientes (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(100) NOT NULL,
                cpf varchar(20) NOT NULL,
                telefone varchar(20),
                email varchar(50),
                endereco varchar(200),
                ativo varchar(3) DEFAULT 'Sim'
            );

            CREATE TABLE IF NOT EXISTS fornecedores (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(100) NOT NULL,
                pessoa varchar(10) DEFAULT 'F',
                cpf varchar(20) NOT NULL,
                telefone varchar(20),
                email varchar(50),
                endereco varchar(200),
                ativo varchar(3) DEFAULT 'Sim'
            );

            CREATE TABLE IF NOT EXISTS arquivos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                tipo varchar(20) NOT NULL,
                id_ref integer NOT NULL,
                nome varchar(100) NOT NULL,
                foto varchar(500) NOT NULL,
                data_validade timestamp
            );
            """,
            ct);
    }

    private static async Task EnsureCatalogSchemaAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE IF EXISTS produtos
              ADD COLUMN IF NOT EXISTS descricao varchar(255),
              ADD COLUMN IF NOT EXISTS estoque integer DEFAULT 0,
              ADD COLUMN IF NOT EXISTS valor_venda numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS valor_compra numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS lucro numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS fornecedor integer,
              ADD COLUMN IF NOT EXISTS categoria integer,
              ADD COLUMN IF NOT EXISTS nivel_estoque integer DEFAULT 0,
              ADD COLUMN IF NOT EXISTS ativo varchar(3) DEFAULT 'Sim',
              ADD COLUMN IF NOT EXISTS foto varchar(100) DEFAULT '';

            CREATE TABLE IF NOT EXISTS categorias (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(100) NOT NULL,
                ativo varchar(3) DEFAULT 'Sim'
            );

            CREATE TABLE IF NOT EXISTS cat_grade (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                produto integer NOT NULL,
                nome varchar(50) NOT NULL
            );

            CREATE TABLE IF NOT EXISTS itens_grade (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                cat_grade integer NOT NULL,
                label varchar(50) NOT NULL,
                estoque integer DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS grade_variant (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                produto integer NOT NULL,
                itens_grade_1 integer,
                itens_grade_2 integer,
                estoque integer DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS entradas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                produto integer NOT NULL,
                quantidade integer NOT NULL,
                motivo varchar(200),
                usuario integer NOT NULL,
                data timestamp NOT NULL DEFAULT NOW(),
                tipo varchar(20) DEFAULT 'Entry'
            );

            CREATE TABLE IF NOT EXISTS saidas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                produto integer NOT NULL,
                quantidade integer NOT NULL,
                motivo varchar(200),
                usuario integer NOT NULL,
                data timestamp NOT NULL DEFAULT NOW(),
                tipo varchar(20) DEFAULT 'Exit'
            );

            CREATE TABLE IF NOT EXISTS detalhes_grade (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                tipo_movimento varchar(20) NOT NULL,
                id_movimento integer NOT NULL,
                id_item_grade integer NOT NULL,
                quantidade integer NOT NULL
            );
            """,
            ct);
    }

    private static async Task EnsureSalesSchemaAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS caixa (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                terminal integer NOT NULL,
                operador integer NOT NULL,
                status varchar(10) NOT NULL DEFAULT 'Aberto',
                fundo_inicial numeric NOT NULL DEFAULT 0,
                total_vendido numeric NOT NULL DEFAULT 0,
                contado numeric,
                quebra numeric,
                data_abertura timestamp NOT NULL DEFAULT NOW(),
                data_fechamento timestamp
            );

            CREATE TABLE IF NOT EXISTS itens_venda (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                caixa integer NOT NULL,
                produto integer NOT NULL,
                codigo varchar(50) NOT NULL,
                quantidade integer NOT NULL,
                valor_unitario numeric NOT NULL,
                venda integer NOT NULL DEFAULT 0,
                grade_opcoes text,
                status varchar(20) NOT NULL DEFAULT 'PendenteGrade'
            );

            CREATE TABLE IF NOT EXISTS sangrias (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                caixa integer NOT NULL,
                valor numeric NOT NULL,
                data timestamp NOT NULL DEFAULT NOW()
            );

            ALTER TABLE IF EXISTS receber
              ADD COLUMN IF NOT EXISTS empresa integer NOT NULL DEFAULT 0,
              ADD COLUMN IF NOT EXISTS caixa integer,
              ADD COLUMN IF NOT EXISTS forma_pgto integer,
              ADD COLUMN IF NOT EXISTS cliente integer,
              ADD COLUMN IF NOT EXISTS subtotal numeric,
              ADD COLUMN IF NOT EXISTS desconto numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS troco numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS comissao_venda numeric DEFAULT 0,
              ADD COLUMN IF NOT EXISTS operador integer,
              ADD COLUMN IF NOT EXISTS cancelado varchar(3) DEFAULT 'Não',
              ADD COLUMN IF NOT EXISTS data_venda timestamp;
            """,
            ct);
    }

    private static async Task WidenLegacyColumnsAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE IF EXISTS usuarios
              ALTER COLUMN senha_crip TYPE varchar(255),
              ALTER COLUMN senha TYPE varchar(255);
            """,
            ct);
    }

    private static async Task SeedGlobalConfigAsync(LegacySasDbContext db, CancellationToken ct)
    {
        if (await db.Configs.AnyAsync(c => c.CompanyId == 0, ct))
            return;

        db.Configs.Add(new LegacyConfigRow
        {
            CompanyId = 0,
            TrialDays = 7,
            BlockDays = 5,
            BlockMessage = "Conta suspensa. Entre em contato com o suporte.",
        });

        await db.SaveChangesAsync(ct);
    }
}
