using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RetailOps.Infrastructure.Legacy.Persistence.Entities;

namespace RetailOps.Infrastructure.Legacy.Persistence;

public static class LegacyDatabaseBootstrap
{
    public static async Task EnsureDevSchemaAsync(IServiceProvider services, CancellationToken ct = default)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<LegacySasDbContext>();

        await db.Database.EnsureCreatedAsync(ct);
        await WidenLegacyColumnsAsync(db, ct);
        await EnsureStoreSettingsSchemaAsync(db, ct);
        await SeedGlobalConfigAsync(db, ct);
    }

    private static async Task EnsureStoreSettingsSchemaAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE IF EXISTS config
              ADD COLUMN IF NOT EXISTS nome_sistema varchar(100),
              ADD COLUMN IF NOT EXISTS contatos varchar(200),
              ADD COLUMN IF NOT EXISTS cnpj_sistema varchar(20),
              ADD COLUMN IF NOT EXISTS endereco varchar(200),
              ADD COLUMN IF NOT EXISTS tipo_rel varchar(10),
              ADD COLUMN IF NOT EXISTS tipo_desconto varchar(10),
              ADD COLUMN IF NOT EXISTS comissao numeric,
              ADD COLUMN IF NOT EXISTS token varchar(100),
              ADD COLUMN IF NOT EXISTS foto_rel varchar(200);

            CREATE TABLE IF NOT EXISTS forma_pgtos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(50) NOT NULL,
                acrescimo numeric DEFAULT 0,
                ativo varchar(3) DEFAULT 'Sim'
            );

            CREATE TABLE IF NOT EXISTS caixas (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                empresa integer NOT NULL,
                nome varchar(50) NOT NULL,
                status varchar(10) DEFAULT 'Fechado',
                operador integer
            );
            """,
            ct);
    }

    private static async Task WidenLegacyColumnsAsync(LegacySasDbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE IF EXISTS usuarios
              ALTER COLUMN senha_crip TYPE varchar(255),
              ALTER COLUMN senha TYPE varchar(255);
            """,
            ct);
    }

    private static async Task SeedGlobalConfigAsync(LegacySasDbContext db, CancellationToken ct)
    {
        if (await db.Configs.AnyAsync(c => c.CompanyId == 0, ct))
            return;

        db.Configs.Add(new LegacyConfigRow
        {
            CompanyId = 0,
            TrialDays = 7,
            BlockDays = 5,
            BlockMessage = "Conta suspensa. Entre em contato com o suporte.",
        });

        await db.SaveChangesAsync(ct);
    }
}
