<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RetailOps.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RetailOps.Shared.Kernel\RetailOps.Shared.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RetailOps.Infrastructure.Legacy" />
    <InternalsVisibleTo Include="RetailOps.UnitTests" />
    <InternalsVisibleTo Include="RetailOps.IntegrationTests" />
  </ItemGroup>
</Project>
