using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RetailOps.Infrastructure.Persistence.Contexts;

namespace RetailOps.Infrastructure.Cutover;

public static class CutoverDatabaseBootstrap
{
    public static async Task EnsureSchemaAsync(IServiceProvider services, CancellationToken ct = default)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<RetailOpsDbContext>();

        // Hand-authored migrations are not registered in EF history; legacy bootstrap may
        // already have created the database, so EnsureCreated/Migrate skip new cutover tables.
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS migration_checkpoints (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" integer NOT NULL,
                "BoundedContext" character varying(64) NOT NULL,
                "RowCount" bigint NOT NULL,
                "SampleChecksum" bigint NOT NULL,
                "CompletedAtUtc" timestamp with time zone NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_migration_checkpoints_TenantId_BoundedContext"
                ON migration_checkpoints ("TenantId", "BoundedContext");

            CREATE TABLE IF NOT EXISTS migration_parallel_run_stats (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" integer NOT NULL,
                "DivergencePercent" numeric NOT NULL,
                "RecordedAtUtc" timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_migration_parallel_run_stats_RecordedAtUtc"
                ON migration_parallel_run_stats ("RecordedAtUtc");
            """,
            ct);
    }
}
