-- Minimal legacy schema for local dev (also created via LegacyDatabaseBootstrap on API startup).

CREATE TABLE IF NOT EXISTS empresas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    telefone varchar(20),
    email varchar(50),
    cpf varchar(20),
    cnpj varchar(20),
    ativo varchar(3) NOT NULL DEFAULT 'Sim',
    data_pgto timestamp,
    valor numeric NOT NULL DEFAULT 0,
    teste varchar(3) NOT NULL DEFAULT 'Não'
);

CREATE TABLE IF NOT EXISTS usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    email varchar(50),
    cpf varchar(20),
    senha_crip varchar(255),
    senha varchar(255),
    nivel varchar(50) NOT NULL DEFAULT 'Operador',
    ativo varchar(3) NOT NULL DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS acessos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave varchar(50) NOT NULL,
    nome varchar(100) NOT NULL,
    grupo integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS usuarios_permissoes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario integer NOT NULL,
    permissao integer NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    codigo varchar(50) NOT NULL,
    nome varchar(100) NOT NULL,
    descricao varchar(255),
    estoque integer DEFAULT 0,
    valor_venda numeric DEFAULT 0,
    valor_compra numeric DEFAULT 0,
    lucro numeric DEFAULT 0,
    fornecedor integer,
    categoria integer,
    nivel_estoque integer DEFAULT 0,
    ativo varchar(3) DEFAULT 'Sim',
    foto varchar(100) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS categorias (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(100) NOT NULL,
    ativo varchar(3) DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS cat_grade (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    produto integer NOT NULL,
    nome varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS itens_grade (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    cat_grade integer NOT NULL,
    label varchar(50) NOT NULL,
    estoque integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS grade_variant (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    produto integer NOT NULL,
    itens_grade_1 integer,
    itens_grade_2 integer,
    estoque integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS entradas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    produto integer NOT NULL,
    quantidade integer NOT NULL,
    motivo varchar(200),
    usuario integer NOT NULL,
    data timestamp NOT NULL DEFAULT NOW(),
    tipo varchar(20) DEFAULT 'Entry'
);

CREATE TABLE IF NOT EXISTS saidas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    produto integer NOT NULL,
    quantidade integer NOT NULL,
    motivo varchar(200),
    usuario integer NOT NULL,
    data timestamp NOT NULL DEFAULT NOW(),
    tipo varchar(20) DEFAULT 'Exit'
);

CREATE TABLE IF NOT EXISTS detalhes_grade (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    tipo_movimento varchar(20) NOT NULL,
    id_movimento integer NOT NULL,
    id_item_grade integer NOT NULL,
    id_item_grade_2 integer,
    quantidade integer NOT NULL
);

CREATE TABLE IF NOT EXISTS contratos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    texto text NOT NULL DEFAULT '',
    data timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    dias_teste integer,
    dias_bloqueio integer,
    msg_bloqueio text,
    nome_sistema varchar(100),
    contatos varchar(200),
    cnpj_sistema varchar(20),
    endereco varchar(200),
    tipo_rel varchar(10),
    tipo_desconto varchar(10),
    comissao numeric,
    token varchar(100),
    foto_rel varchar(200)
);

CREATE TABLE IF NOT EXISTS forma_pgtos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    acrescimo numeric DEFAULT 0,
    ativo varchar(3) DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS caixas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    status varchar(10) DEFAULT 'Fechado',
    operador integer
);

CREATE TABLE IF NOT EXISTS caixa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    terminal integer NOT NULL,
    operador integer NOT NULL,
    status varchar(10) NOT NULL DEFAULT 'Aberto',
    fundo_inicial numeric NOT NULL DEFAULT 0,
    total_vendido numeric NOT NULL DEFAULT 0,
    contado numeric,
    quebra numeric,
    data_abertura timestamp NOT NULL DEFAULT NOW(),
    data_fechamento timestamp
);

CREATE TABLE IF NOT EXISTS itens_venda (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    caixa integer NOT NULL,
    produto integer NOT NULL,
    codigo varchar(50) NOT NULL,
    quantidade integer NOT NULL,
    valor_unitario numeric NOT NULL,
    venda integer NOT NULL DEFAULT 0,
    grade_opcoes text,
    status varchar(20) NOT NULL DEFAULT 'PendenteGrade'
);

CREATE TABLE IF NOT EXISTS sangrias (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    caixa integer NOT NULL,
    valor numeric NOT NULL,
    data timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS receber (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL DEFAULT 0,
    tipo varchar(20) NOT NULL,
    descricao varchar(100),
    pessoa integer NOT NULL,
    valor numeric NOT NULL,
    data_venc timestamp NOT NULL,
    pago varchar(3) NOT NULL DEFAULT 'Não',
    caixa integer,
    forma_pgto integer,
    cliente integer,
    subtotal numeric,
    desconto numeric DEFAULT 0,
    troco numeric DEFAULT 0,
    comissao_venda numeric DEFAULT 0,
    operador integer,
    cancelado varchar(3) DEFAULT 'Não',
    data_venda timestamp
);

CREATE TABLE IF NOT EXISTS pagar (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    tipo varchar(30) NOT NULL,
    descricao varchar(255) NOT NULL,
    pessoa integer NOT NULL DEFAULT 0,
    valor numeric NOT NULL,
    data_venc timestamp NOT NULL,
    pago varchar(3) NOT NULL DEFAULT 'Não',
    frequencia_dias integer,
    id_ref integer,
    data_pgto timestamp,
    data_lanc timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comissoes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    descricao varchar(50) NOT NULL DEFAULT 'Comissão venda',
    valor numeric NOT NULL,
    vendedor integer NOT NULL,
    id_ref integer NOT NULL,
    pago varchar(3) NOT NULL DEFAULT 'Não',
    data_lanc timestamp NOT NULL DEFAULT NOW(),
    data_pgto timestamp,
    pagar_id integer
);

CREATE TABLE IF NOT EXISTS clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(100) NOT NULL,
    cpf varchar(20) NOT NULL,
    telefone varchar(20),
    email varchar(50),
    endereco varchar(200),
    ativo varchar(3) DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS fornecedores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(100) NOT NULL,
    pessoa varchar(10) DEFAULT 'F',
    cpf varchar(20) NOT NULL,
    telefone varchar(20),
    email varchar(50),
    endereco varchar(200),
    ativo varchar(3) DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS arquivos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    tipo varchar(20) NOT NULL,
    id_ref integer NOT NULL,
    nome varchar(100) NOT NULL,
    foto varchar(500) NOT NULL,
    data_validade timestamp
);

INSERT INTO config (empresa, dias_teste, dias_bloqueio, msg_bloqueio)
SELECT 0, 7, 5, 'Conta suspensa. Entre em contato com o suporte.'
WHERE NOT EXISTS (SELECT 1 FROM config WHERE empresa = 0);
