-- Minimal legacy schema for local dev (also created via LegacyDatabaseBootstrap on API startup).

CREATE TABLE IF NOT EXISTS empresas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    telefone varchar(20),
    email varchar(50),
    cpf varchar(20),
    cnpj varchar(20),
    ativo varchar(3) NOT NULL DEFAULT 'Sim',
    data_pgto timestamp,
    valor numeric NOT NULL DEFAULT 0,
    teste varchar(3) NOT NULL DEFAULT 'Não'
);

CREATE TABLE IF NOT EXISTS usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    email varchar(50),
    cpf varchar(20),
    senha_crip varchar(255),
    senha varchar(255),
    nivel varchar(50) NOT NULL DEFAULT 'Operador',
    ativo varchar(3) NOT NULL DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS acessos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave varchar(50) NOT NULL,
    nome varchar(100) NOT NULL,
    grupo integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS usuarios_permissoes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario integer NOT NULL,
    permissao integer NOT NULL
);

CREATE TABLE IF NOT EXISTS produtos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    codigo varchar(50) NOT NULL,
    nome varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS contratos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    texto text NOT NULL DEFAULT '',
    data timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    dias_teste integer,
    dias_bloqueio integer,
    msg_bloqueio text,
    nome_sistema varchar(100),
    contatos varchar(200),
    cnpj_sistema varchar(20),
    endereco varchar(200),
    tipo_rel varchar(10),
    tipo_desconto varchar(10),
    comissao numeric,
    token varchar(100),
    foto_rel varchar(200)
);

CREATE TABLE IF NOT EXISTS forma_pgtos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    acrescimo numeric DEFAULT 0,
    ativo varchar(3) DEFAULT 'Sim'
);

CREATE TABLE IF NOT EXISTS caixas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa integer NOT NULL,
    nome varchar(50) NOT NULL,
    status varchar(10) DEFAULT 'Fechado',
    operador integer
);

CREATE TABLE IF NOT EXISTS receber (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo varchar(20) NOT NULL,
    pessoa integer NOT NULL,
    valor numeric NOT NULL,
    data_venc timestamp NOT NULL,
    pago varchar(3) NOT NULL DEFAULT 'Não'
);

INSERT INTO config (empresa, dias_teste, dias_bloqueio, msg_bloqueio)
SELECT 0, 7, 5, 'Conta suspensa. Entre em contato com o suporte.'
WHERE NOT EXISTS (SELECT 1 FROM config WHERE empresa = 0);
