<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RetailOps.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RetailOps.Infrastructure\RetailOps.Infrastructure.csproj" />
    <ProjectReference Include="..\RetailOps.Infrastructure.Legacy\RetailOps.Infrastructure.Legacy.csproj" />
    <ProjectReference Include="..\RetailOps.Identity.Infrastructure\RetailOps.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\RetailOps.Identity.Core\RetailOps.Identity.Core.csproj" />
    <ProjectReference Include="..\RetailOps.Core\RetailOps.Core.csproj" />
  </ItemGroup>
</Project>
